namespace Unity.XR.PXR
{
	public enum BodyTrackingErrorCode
	{
		BT_ERROR_INNER_EXCEPTION = 0,
		BT_ERROR_TRACKER_NOT_CALIBRATED = 1,
		BT_ERROR_TRACKER_NUM_NOT_ENOUGH = 2,
		BT_ERROR_TRACKER_STATE_NOT_SATISFIED = 3,
		BT_ERROR_TRACKER_PERSISTENT_INVISIBILITY = 4,
		BT_ERROR_TRACKER_DATA_ERROR = 5,
		BT_ERROR_USER_CHANGE = 6,
		BT_ERROR_TRACKING_POSE_ERROR = 7
	}
}
