namespace Unity.XR.PXR
{
	public enum ConfigType
	{
		RenderTextureWidth = 0,
		RenderTextureHeight = 1,
		ShowFps = 2,
		RuntimeLogLevel = 3,
		PluginLogLevel = 4,
		UnityLogLevel = 5,
		UnrealLogLevel = 6,
		NativeLogLevel = 7,
		TargetFrameRate = 8,
		NeckModelX = 9,
		NeckModelY = 10,
		NeckModelZ = 11,
		DisplayRefreshRate = 12,
		Ability6Dof = 13,
		DeviceModel = 14,
		PhysicalIPD = 15,
		ToDelaSensorY = 16,
		SystemDisplayRate = 17,
		FoveationSubsampledEnabled = 18,
		TrackingOriginHeight = 19,
		EngineVersion = 20,
		UnrealOpenglNoError = 21,
		EnableCPT = 22,
		MRCTextureID = 23,
		RenderFPS = 24,
		AntiAliasingLevelRecommended = 25,
		MRCTextureID2 = 26,
		PxrSetSurfaceView = 27,
		PxrAPIVersion = 28,
		PxrMrcPosiyionYOffset = 29,
		PxrMrcTextureWidth = 30,
		PxrMrcTextureHeight = 31,
		PxrAndroidLayerDimensions = 34,
		PxrANDROID_SN = 35,
		PxrSetDesiredFPS = 36,
		PxrGetSeethroughState = 37,
		PxrSetLayerBlend = 38,
		PxrLeftEyeFOV = 39,
		PxrRightEyeFOV = 40,
		PxrBothEyeFOV = 41,
		SupportQuickSeethrough = 42,
		SetFilterType = 43,
		SetSubmitLayerEXTItemColorMatrix = 44
	}
}
