namespace Unity.XR.PXR
{
	public enum PxrControllerKeyMap
	{
		PXR_CONTROLLER_KEY_HOME = 0,
		PXR_CONTROLLER_KEY_AX = 1,
		PXR_CONTROLLER_KEY_BY = 2,
		PXR_CONTROLLER_KEY_BACK = 3,
		PXR_CONTROLLER_KEY_TRIGGER = 4,
		PXR_CONTROLLER_KEY_VOL_UP = 5,
		PXR_CONTROLLER_KEY_VOL_DOWN = 6,
		PXR_CONTROLLER_KEY_ROCKER = 7,
		PXR_CONTROLLER_KEY_GRIP = 8,
		PXR_CONTROLLER_KEY_TOUCHPAD = 9,
		PXR_CONTROLLER_KEY_LASTONE = 127,
		PXR_CONTROLLER_TOUCH_AX = 128,
		PXR_CONTROLLER_TOUCH_BY = 129,
		PXR_CONTROLLER_TOUCH_ROCKER = 130,
		PXR_CONTROLLER_TOUCH_TRIGGER = 131,
		PXR_CONTROLLER_TOUCH_THUMB = 132,
		PXR_CONTROLLER_TOUCH_LASTONE = 255
	}
}
