namespace Unity.XR.PXR
{
	public enum PxrDeviceEventType
	{
		CONNECTCHANGED = 0,
		MAIN_CHANGED = 1,
		VERSION = 2,
		SN = 3,
		BIND_STATUS = 4,
		PXR_STATION_STATUS = 5,
		IOBUSY = 6,
		OTASTAUS = 7,
		ID = 8,
		OTASATAION_PROGRESS = 9,
		OTASATAION_CODE = 10,
		OTACONTROLLER_PROGRESS = 11,
		OTACONTROLLER_CODE = 12,
		OTA_SUCCESS = 13,
		BLEMAC = 14,
		HANDNESS_CHANGED = 15,
		CHANNEL = 16,
		LOSSRATE = 17,
		THREAD_STARTED = 18,
		MENUPRESSED_STATE = 19,
		HANDTRACKING_SETTING = 20,
		INPUTDEVICE_CHANGED = 21,
		SYSTEMGESTURE_STATE = 22,
		MOTION_TRACKER_STATE = 23,
		MOTION_TRACKER_BATTERY = 24,
		BODYTRACKING_STATE_ERROR_CODE = 25,
		BODYTRACKING_ACTION = 26
	}
}
