namespace Unity.XR.PXR
{
	public enum TrackingStateCode
	{
		PXR_MT_SUCCESS = 0,
		PXR_MT_FAILURE = -1,
		PXR_MT_MODE_NONE = -2,
		PXR_MT_DEVICE_NOT_SUPPORT = -3,
		PXR_MT_SERVICE_NEED_START = -4,
		PXR_MT_ET_PERMISSION_DENIED = -5,
		PXR_MT_FT_PERMISSION_DENIED = -6,
		PXR_MT_MIC_PERMISSION_DENIED = -7,
		PXR_MT_SYSTEM_DENIED = -8,
		PXR_MT_UNKNOW_ERROR = -9
	}
}
