namespace Unity.XR.PICO.TOBSupport
{
	public enum PICOCastOptionValueEnum
	{
		OPTION_VALUE_RESOLUTION_HIGH = 0,
		OPTION_VALUE_RESOLUTION_MIDDLE = 1,
		OPTION_VALUE_RESOLUTION_AUTO = 2,
		OPTION_VALUE_RESOLUTION_HIGH_2K = 3,
		OPTION_VALUE_RESOLUTION_HIGH_4K = 4,
		OPTION_VALUE_BITRATE_HIGH = 5,
		OPTION_VALUE_BITRATE_MIDDLE = 6,
		OPTION_VALUE_BITRATE_LOW = 7,
		OPTION_VALUE_AUDIO_ON = 8,
		OPTION_VALUE_AUDIO_OFF = 9,
		STATUS_VALUE_STATE_STARTED = 10,
		STATUS_VALUE_STATE_STOPPED = 11,
		STATUS_VALUE_ERROR = 12
	}
}
